### ISSUE TITLE
Support for Portuguese Language

### ISSUE THREAD

**Issue by rogeriobiondi** [daad-adventure-writer/daad#2]
Hello,

I'm using Daad but there are some characters that are not supported in Portuguese language, such as 'á' and 'ç'. Daad supports Spanish which is a latin language. How difficult would be to support Portuguese, since both are similar? Is there any way to print the accents using the special character #(code)? Thank you very much.

**Comment by rogeriobiondi** [comment]
According the manual, should be possible mapping special characters using the \ (in DAAD #) character. I saw that á, é, í, ó, ú and ç are already covered. But would be great having some additional accents such as:

#Q ... à
#R ... ã
#S ... õ
#T ... â
#U ... ê
#V ... ô

Thank you very much
Best regards

**Comment by Utodev** [comment]
I would have a  look at it. I'm closing this issue and I opened another one in DRC (the new DAAD compiler) github site, cause it's there where it can be done. 

Find it here:
https://github.com/daad-adventure-writer/DRC/issues/22
