### ISSUE TITLE
Ability to export to .z5/.z6?

### ISSUE THREAD

**Issue by vanfanel** [daad-adventure-writer/daad#3]
Hi there

I have just discovered this project, and I was wondering if, in the vein of UnQuill [(UnQuill)](https://www.seasip.info/Unix/UnQuill/) would it be possible to export DAAD games to .z5 or .z6 (with graphics in .BLB files, etc).
Also, is there a DAAD interpreter for GNU/Linux?

Thanks!

**Comment by vanfanel** [comment]
Also, @Utodev , are you the author of this? --> [Pawer intérptere de PAWS](http://www.caad.es/fichas/pawer.html)

**Comment by Utodev** [comment]
DRC compiler has a front end (takes DAAD source file and converts that to a JSON) and a back-end (takes that JSON and converts it into a DDB file that can be run by the DAAD interpreters). Replacing the back end with another back end which generates Inform or ZIL code is possible, but it's not something in my roadmap. "Pawer" would be a nice point to start with the Inform version, as it would avoid to use the Inform library, and still get a Z3 or Z5 file.

I would be happy if someone does a new back end, but at the moment it's sure it's not going to be myself doing it, sorry.

**Comment by DjMorgul** [comment]
@vanfanel there's a DAAD interpreter that works under Linux, NAPS: https://github.com/daad-adventure-writer/NAPS
